---

- name: Start redis container
  containers.podman.podman_container:
    name: redis
    image: registry.redhat.io/rhel8/redis-5:1
    state: started
    restart: yes
    restart_policy: "always"
    ports:
        - "6379:6379"
    env:
        REDIS_PASSWORD: "{{ redis_password }}"

- name: Create redis systemd service file
  command: >
    podman generate systemd -n -f redis
  args:
    chdir: '/tmp/'

- name: Write reids systemd unit file
  copy:
    src: '/tmp/container-redis.service'
    dest: '/usr/lib/systemd/system/container-redis.service'
    remote_src: true

- name: Remove temp unit file
  file:
    path: '/tmp/container-redis.service'
    state: absent

- name: Force systemd to reread configs
  ansible.builtin.systemd:
    daemon_reload: yes
